LOCATION_MAPPING = {

    --Destiny Island
    [2656705] = {"@Overview/Destiny Islands/Seashore - Log under Bridge (Day 1)"},
    [2656704] = {"@Overview/Destiny Islands/Seashore - Log on Riku's Island (Day 1)"},
    [2656706] = {"@Overview/Destiny Islands/Seashore - Gather Cloth (Day 1)"},
    [2656707] = {"@Overview/Destiny Islands/Seashore - Gather Rope (Day 1)"},
    [2656700] = {"@Overview/Destiny Islands/Seashore - Capture Fish 1 (Day 2)"},
    [2656701] = {"@Overview/Destiny Islands/Seashore - Capture Fish 2 (Day 2)"},
    [2656702] = {"@Overview/Destiny Islands/Seashore - Capture Fish 3 (Day 2)"},
    [2656703] = {"@Overview/Destiny Islands/Seashore - Gather Seagull Egg (Day 2)"},
    [2656711] = {"@Overview/Destiny Islands/Secret Place - Gather Mushroom (Day 2)"},
    [2656712] = {"@Overview/Destiny Islands/Cove - Gather Mushroom Near Zip Line (Day 2)"},
    [2656713] = {"@Overview/Destiny Islands/Cove - Gather Mushroom in Small Cave (Day 2)"},
    [2656714] = {"@Overview/Destiny Islands/Cove - Talk to Kairi (Day 2)"},
    [2650011] = {"@Overview/Destiny Islands/Cove - Destiny Islands Chest"},
    [2656715] = {"@Overview/Destiny Islands/Gather Drinking Water (Day 2)"},

    -- Traverse Town
    [2650212] = {"@Overview/Traverse Town - 1st Visit/1st District - Accessory Shop Roof Chest"},
    [2650213] = {"@Overview/Traverse Town - 1st Visit/2nd District - Boots and Shoes Awning Chest"},
    [2650214] = {"@Overview/Traverse Town - 1st Visit/2nd District - Rooftop Chest"},
    [2650251] = {"@Overview/Traverse Town - 1st Visit/2nd District - Gizmo Shop Facade Chest"},
    [2650252] = {"@Overview/Traverse Town - 1st Visit/Alleyway - Balcony Chest"},
    [2650253] = {"@Overview/Traverse Town - 1st Visit/Alleyway - Blue Room Awning Chest"},
    [2650254] = {"@Overview/Traverse Town - 1st Visit/Alleyway - Corner Chest"},
    [2650292] = {"@Overview/Traverse Town - 1st Visit/Green Room - Clock Puzzle Chest"},
    [2650293] = {"@Overview/Traverse Town - 1st Visit/Green Room - Table Chest"},
    [2650294] = {"@Overview/Traverse Town - 1st Visit/Red Room Chest"},
    [2650332] = {"@Overview/Traverse Town - 1st Visit/Accessory Shop Chest"},
    [2650894] = {"@Overview/Traverse Town - 1st Visit/Secret Waterway - Chest Near Stairs"},
    [2656011] = {"@Overview/Traverse Town - 1st Visit/Guard Armor Rewards"},
    [2656012] = {"@Overview/Traverse Town - 1st Visit/Guard Armor Rewards"},
    [2656013] = {"@Overview/Traverse Town - 1st Visit/Guard Armor Rewards"},
    [2656520] = {"@Overview/Traverse Town - 1st Visit/Defeat Leon - MISSABLE"},
    [2656014] = {"@Overview/Traverse Town - 1st Visit/Secret Waterway - Leon"},
    [2656016] = {"@Overview/Traverse Town - 1st Visit/Defeat Guard Armor"},
    [2656375] = {"@Overview/Traverse Town - 1st Visit/1st District - Talk to Cid"},
    [2656521] = {"@Overview/Traverse Town - 1st Visit/1st District - Talk to Aerith before Defeating Guard Armor - MISSABLE"},

    [2656311] = {"@Overview/Traverse Town - Further Visits/Merlin - All Arts Items"},
    [2656312] = {"@Overview/Traverse Town - Further Visits/Merlin - All LV1 Magic"},
    [2656313] = {"@Overview/Traverse Town - Further Visits/Merlin - All LV3 Magic"},
    [2650211] = {"@Overview/Traverse Town - Further Visits/1st District - Candle Puzzle Chest"},
    [2650891] = {"@Overview/Traverse Town - Further Visits/Mystical House - Glide Chest"},
    [2650892] = {"@Overview/Traverse Town - Further Visits/Alleyway - Chest Behind Crates"},
    [2656015] = {"@Overview/Traverse Town - Further Visits/Secret Waterway - Kairi"},
    [2656131] = {"@Overview/Traverse Town - Further Visits/Defeat Opposite Armor"},

    [2656500] = {"@Overview/Traverse Town - Postcards/Hit Fan in Item Shop"},
    [2656501] = {"@Overview/Traverse Town - Postcards/Open Safe in 1st District"},
    [2656502] = {"@Overview/Traverse Town - Postcards/Activate Clock in Gizmo Shop"},
    [2656503] = {"@Overview/Traverse Town - Postcards/Activate Clock in Gizmo Shop"},
    [2656505] = {"@Overview/Traverse Town - Postcards/3rd District Balcony"},
    [2656120] = {"@Overview/Traverse Town - Postcards/Mail Postcard 01"},
    [2656121] = {"@Overview/Traverse Town - Postcards/Mail Postcard 02"},
    [2656122] = {"@Overview/Traverse Town - Postcards/Mail Postcard 03"},
    [2656123] = {"@Overview/Traverse Town - Postcards/Mail Postcard 04"},
    [2656124] = {"@Overview/Traverse Town - Postcards/Mail Postcard 05"},
    [2656125] = {"@Overview/Traverse Town - Postcards/Mail Postcard 06"},
    [2656126] = {"@Overview/Traverse Town - Postcards/Mail Postcard 07"},
    [2656127] = {"@Overview/Traverse Town - Postcards/Mail Postcard 08"},
    [2656128] = {"@Overview/Traverse Town - Postcards/Mail Postcard 09"},
    [2656129] = {"@Overview/Traverse Town - Postcards/Mail Postcard 10"},

    [2656504] = {"@Overview/Traverse Town - Moogle Workshop/Postcard Behind Poster"},
    [2650371] = {"@Overview/Traverse Town - Moogle Workshop/Right Chest"},
    [2650893] = {"@Overview/Traverse Town - Moogle Workshop/Left Chest"},
    [2656401] = {"@Overview/Traverse Town - Moogle Workshop/Synth Log"},
    [2656402] = {"@Overview/Traverse Town - Moogle Workshop/Synth Cloth"},
    [2656403] = {"@Overview/Traverse Town - Moogle Workshop/Synth Rope"},
    [2656404] = {"@Overview/Traverse Town - Moogle Workshop/Synth Seagull Egg"},
    [2656405] = {"@Overview/Traverse Town - Moogle Workshop/Synth Fish"},
    [2656406] = {"@Overview/Traverse Town - Moogle Workshop/Synth Mushroom"},

    [2656506] = {"@Overview/Traverse Town - Gepetto's House/Postcard in Bowl"},
    [2650334] = {"@Overview/Traverse Town - Gepetto's House/Chest"},
    [2656304] = {"@Overview/Traverse Town - Gepetto's House/Gepetto's Rewards"},
    [2656305] = {"@Overview/Traverse Town - Gepetto's House/Gepetto's Rewards"},
    [2656306] = {"@Overview/Traverse Town - Gepetto's House/Gepetto's Rewards"},
    [2656307] = {"@Overview/Traverse Town - Gepetto's House/Gepetto's Rewards"},
    [2656308] = {"@Overview/Traverse Town - Gepetto's House/Gepetto's Rewards"},
    [2656309] = {"@Overview/Traverse Town - Gepetto's House/All Summons Rewards"},
    [2656310] = {"@Overview/Traverse Town - Gepetto's House/Talk to Pinocchio"},

    [2656314] = {"@Overview/Traverse Town - Puppies/Return 10 Puppies"},
    [2656315] = {"@Overview/Traverse Town - Puppies/Return 20 Puppies"},
    [2656316] = {"@Overview/Traverse Town - Puppies/Return 30 Puppies"},
    [2656317] = {"@Overview/Traverse Town - Puppies/Return 40 Puppies"},
    [2656318] = {"@Overview/Traverse Town - Puppies/Return 50 Puppies"},
    [2656319] = {"@Overview/Traverse Town - Puppies/Return 50 Puppies"},
    [2656320] = {"@Overview/Traverse Town - Puppies/Return 60 Puppies"},
    [2656321] = {"@Overview/Traverse Town - Puppies/Return 70 Puppies"},
    [2656322] = {"@Overview/Traverse Town - Puppies/Return 80 Puppies"},
    [2656324] = {"@Overview/Traverse Town - Puppies/Return 90 Puppies"},
    [2656326] = {"@Overview/Traverse Town - Puppies/Return 99 Puppies"},
    [2656327] = {"@Overview/Traverse Town - Puppies/Return 99 Puppies"},

    -- Wonderland

    [2650932] = {"@Overview/Wonderland - Before Footprints/Rabbit Hole - Defeat Heartless 1"},
    [2650933] = {"@Overview/Wonderland - Before Footprints/Rabbit Hole - Defeat Heartless 2"},
    [2650934] = {"@Overview/Wonderland - Before Footprints/Rabbit Hole - Defeat Heartless 3"},
    [2651011] = {"@Overview/Wonderland - Before Footprints/Queen's Castle - Left Hedge Chest"},
    [2651012] = {"@Overview/Wonderland - Before Footprints/Queen's Castle - Right Hedge Blue Chest"},
    [2651013] = {"@Overview/Wonderland - Before Footprints/Queen's Castle - Right Hedge Red Chest"},
    [2651052] = {"@Overview/Wonderland - Before Footprints/Lotus Forest - Southwest Corner Chest"},
    [2651053] = {"@Overview/Wonderland - Before Footprints/Lotus Forest - Chest Near Nut"},
    [2651054] = {"@Overview/Wonderland - Before Footprints/Lotus Forest - Northeast Corner Chest"},
    [2651094] = {"@Overview/Wonderland - Before Footprints/Tea Party Garden - 1st Chest Above Lotus Forest Entrance"},
    [2651093] = {"@Overview/Wonderland - Before Footprints/Tea Party Garden - 2nd Chest Above Lotus Forest Entrance"},
    [2656618] = {"@Overview/Wonderland - Before Footprints/Tea Party Garden - Left Cushioned Chair"},
    [2656619] = {"@Overview/Wonderland - Before Footprints/Tea Party Garden - Left Pink Chair"},
    [2656620] = {"@Overview/Wonderland - Before Footprints/Tea Party Garden - Right Yellow Chair"},
    [2656621] = {"@Overview/Wonderland - Before Footprints/Tea Party Garden - Left Gray Chair"},
    [2656622] = {"@Overview/Wonderland - Before Footprints/Tea Party Garden - Right Brown Chair"},
    [2651132] = {"@Overview/Wonderland - Before Footprints/Tea Party Garden - Chest Across Bizarre Room Entrance"},

    [2651014] = {"@Overview/Wonderland - After Footprints/Lotus Forest - Thunder Plant Chest 1"},
    [2651051] = {"@Overview/Wonderland - After Footprints/Lotus Forest - Thunder Plant Chest 2"},
    [2651091] = {"@Overview/Wonderland - After Footprints/Bizarre Room - Lamp Chest"},
    [2651131] = {"@Overview/Wonderland - After Footprints/Tea Party Garden - Bear and Clock Puzzle Chest"},
    [2656376] = {"@Overview/Wonderland - After Footprints/Bizarre Room - Read Book"},
    [2656041] = {"@Overview/Wonderland - After Footprints/Bizarre Room - Defeat Trickmaster"},
    [2656042] = {"@Overview/Wonderland - After Footprints/Bizarre Room - Defeat Trickmaster"},
    [2656385] = {"@Overview/Wonderland - After Footprints/Bizarre Room - Seal Keyhole"},

    [2656613] = {"@Overview/Wonderland - Misc/Bizarre Room - Examine Flower Pot"},
    [2656614] = {"@Overview/Wonderland - Misc/Lotus Forest - Red Flowers on Main Path"},
    [2656615] = {"@Overview/Wonderland - Misc/Lotus Forest - Yellow Flowers in Middle Clearing and Through Painting"},
    [2656616] = {"@Overview/Wonderland - Misc/Lotus Forest - Yellow Elixir Flower Through Painting"},
    [2656617] = {"@Overview/Wonderland - Misc/Lotus Forest - Red Flower Raise Lily Pads"},
    [2656603] = {"@Overview/Wonderland - Misc/Lotus Forest - Blue Trinity in Alcove"},
    [2656604] = {"@Overview/Wonderland - Misc/Lotus Forest - Blue Trinity by Moving Boulder"},

    -- Deep Jungle

    [2651213] = {"@Overview/Deep Jungle - Before Slides/Tree House - Chest Beneath Tree House"},
    [2651214] = {"@Overview/Deep Jungle - Before Slides/Tree House - Rooftop Chest"},
    [2651413] = {"@Overview/Deep Jungle - Before Slides/Tree House - Suspended Boat Chest"},
    [2651251] = {"@Overview/Deep Jungle - Before Slides/Hippo's Lagoon - Center Chest"},
    [2651252] = {"@Overview/Deep Jungle - Before Slides/Hippo's Lagoon - Left Chest"},
    [2651253] = {"@Overview/Deep Jungle - Before Slides/Hippo's Lagoon - Right Chest"},
    [2651291] = {"@Overview/Deep Jungle - Before Slides/Vines - Chest"},
    [2651292] = {"@Overview/Deep Jungle - Before Slides/Vines 2 - Chest"},
    [2651331] = {"@Overview/Deep Jungle - Before Slides/Tunnel - Chest"},
    [2651334] = {"@Overview/Deep Jungle - Before Slides/Tent - Chest"},
    [2651411] = {"@Overview/Deep Jungle - Before Slides/Cliff - Left Chest"},
    [2651412] = {"@Overview/Deep Jungle - Before Slides/Cliff - Right Chest"},
    [2656383] = {"@Overview/Deep Jungle - Before Slides/Tent - Meet Jane"},
    [2656361] = {"@Overview/Deep Jungle - Before Slides/Camp - Oven Experiment"},
    [2656362] = {"@Overview/Deep Jungle - Before Slides/Camp - Research Table Experiment"},
    [2656363] = {"@Overview/Deep Jungle - Before Slides/Camp - Research Table Experiment"},

    [2651371] = {"@Overview/Deep Jungle - After Slides/Waterfall Cavern - Lower Chest"},
    [2651372] = {"@Overview/Deep Jungle - After Slides/Waterfall Cavern - Middle Chest"},
    [2651373] = {"@Overview/Deep Jungle - After Slides/Waterfall Cavern - High Wall Chest"},
    [2651374] = {"@Overview/Deep Jungle - After Slides/Waterfall Cavern - High Middle Chest"},
    [2656021] = {"@Overview/Deep Jungle - After Slides/Bamboo Thicket - Defeat Sabor"},
    [2656022] = {"@Overview/Deep Jungle - After Slides/Cliff - Defeat Clayton"},
    [2656023] = {"@Overview/Deep Jungle - After Slides/Cavern of Hearts - Seal the Keyhole"},
    [2656024] = {"@Overview/Deep Jungle - After Slides/Cavern of Hearts - Seal the Keyhole"},
    [2656384] = {"@Overview/Deep Jungle - After Slides/Cavern of Hearts - Seal the Keyhole"},
    [2656364] = {"@Overview/Deep Jungle - After Slides/Cliff - Save Gorillas"},
    [2656365] = {"@Overview/Deep Jungle - After Slides/Tree House - Save Gorillas"},
    [2656366] = {"@Overview/Deep Jungle - After Slides/Camp - Save Gorillas"},
    [2656367] = {"@Overview/Deep Jungle - After Slides/Bamboo Thicket - Save Gorillas"},
    [2656368] = {"@Overview/Deep Jungle - After Slides/Climbing Trees - Save Gorillas"},


    [2656370] = {"@Overview/Deep Jungle - Jungle Slider/Jungle Slider - Green Serpent"},
    [2656371] = {"@Overview/Deep Jungle - Jungle Slider/Jungle Slider - Splash Tunnel"},
    [2656372] = {"@Overview/Deep Jungle - Jungle Slider/Jungle Slider - Jade Spiral"},
    [2656373] = {"@Overview/Deep Jungle - Jungle Slider/Jungle Slider - Panic Fall"},
    [2656374] = {"@Overview/Deep Jungle - Jungle Slider/Jungle Slider - Shadow Cavern"},

    -- Olympus Coliseum

    [2653332] = {"@Overview/Olympus Coliseum - Before Entry Pass/Coliseum Gates - Chest Behind Left Columns"},
    [2653372] = {"@Overview/Olympus Coliseum - Before Entry Pass/Coliseum Gates - Blizzara Chest"},
    [2653373] = {"@Overview/Olympus Coliseum - Before Entry Pass/Coliseum Gates - Blizzaga Chest"},
    [2656031] = {"@Overview/Olympus Coliseum - Before Entry Pass/Coliseum Lobby - Phil's Training"},
    [2656386] = {"@Overview/Olympus Coliseum - Before Entry Pass/Coliseum Gates - Obtain Entry Pass"},


    [2656330] = {"@Overview/Olympus Coliseum - Cups/Coliseum Lobby - Olympia Chest"},
    [2656369] = {"@Overview/Olympus Coliseum - Cups/Coliseum Gates - Purple Jar"},

    [2656032] = {"@Overview/Olympus Coliseum - After Entry Pass/Coliseum Gates - Talk to Cloud"},
    [2656033] = {"@Overview/Olympus Coliseum - After Entry Pass/Coliseum Lobby - Defeat Cerberus"},
    [2656380] = {"@Overview/Olympus Coliseum - After Entry Pass/Coliseum Lobby - Defeat Cerberus"},

    [2659001] = {"@Overview/Olympus Coliseum - Cups/Phil Cup"},
    [2659002] = {"@Overview/Olympus Coliseum - Cups/Phil Cup"},
    [2659003] = {"@Overview/Olympus Coliseum - Cups/Phil Cup"},

    [2659004] = {"@Overview/Olympus Coliseum - Cups/Pegasus Cup"},
    [2659005] = {"@Overview/Olympus Coliseum - Cups/Pegasus Cup"},
    [2659006] = {"@Overview/Olympus Coliseum - Cups/Pegasus Cup"},
    [2659007] = {"@Overview/Olympus Coliseum - Cups/Hercules Cup"},
    [2659008] = {"@Overview/Olympus Coliseum - Cups/Hercules Cup"},
    [2659009] = {"@Overview/Olympus Coliseum - Cups/Hercules Cup"},
    [2659018] = {"@Overview/Olympus Coliseum - Cups/Hercules Cup"},
    [2659019] = {"@Overview/Olympus Coliseum - Cups/Hercules Cup"},

    [2659010] = {"@Overview/Olympus Coliseum - Cups/Hades Cup"},
    [2659011] = {"@Overview/Olympus Coliseum - Cups/Hades Cup"},
    [2659012] = {"@Overview/Olympus Coliseum - Cups/Hades Cup"},
    [2659013] = {"@Overview/Olympus Coliseum - Cups/Hades Cup"},
    [2659014] = {"@Overview/Olympus Coliseum - Cups/Hades Cup"},
    [2659015] = {"@Overview/Olympus Coliseum - Cups/Hades Cup"},
    [2659016] = {"@Overview/Olympus Coliseum - Cups/Hades Cup"},

    [2659017] = {"@Overview/Olympus Coliseum - Cups/Defeat Hades"},
    [2657011] = {"@Overview/Olympus Coliseum - Cups/Defeat Hades"},
    [2657025] = {"@Overview/Olympus Coliseum - Cups/Defeat Sephiroth"},
    [2656328] = {"@Overview/Olympus Coliseum - Cups/Defeat Sephiroth"},
    [2656329] = {"@Overview/Olympus Coliseum - Cups/Defeat Ice Titan"},


    -- Agrabah

    [2651972] = {"@Overview/Agrabah - Chests/Plaza - Chest by Storage"},
    [2651973] = {"@Overview/Agrabah - Chests/Plaza - Raised Terrace Chest"},
    [2651974] = {"@Overview/Agrabah - Chests/Plaza - Top Corner Chest"},
    [2652011] = {"@Overview/Agrabah - Chests/Alley - Chest"},
    [2652012] = {"@Overview/Agrabah - Chests/Bazaar - Chest Across Windows"},
    [2652013] = {"@Overview/Agrabah - Chests/Bazaar - High Corner Chest"},
    [2652014] = {"@Overview/Agrabah - Chests/Main Street - Right Palace Entrance Chest"},
    [2652051] = {"@Overview/Agrabah - Chests/Main Street - Chest High Above Alley Entrance"},
    [2652052] = {"@Overview/Agrabah - Chests/Main Street - Chest High Above Palace Entrance"},
    [2652053] = {"@Overview/Agrabah - Chests/Palace Gates - Low Chest"},
    [2652054] = {"@Overview/Agrabah - Chests/Palace Gates - High Chest Opposite Palace"},
    [2652091] = {"@Overview/Agrabah - Chests/Palace Gates - High Chest Close to Palace"},
    [2652093] = {"@Overview/Agrabah - Chests/Storage - Chest Behind Barrel"},
    [2652294] = {"@Overview/Agrabah - Chests/Aladdin's House - Chest at Main Street Entrance"},
    [2652331] = {"@Overview/Agrabah - Chests/Aladdin's House - Chest at Plaza Entrance"},
    [2656051] = {"@Overview/Agrabah - Events/Palace Gates - Defeat Pot Centipede"},
    [2656052] = {"@Overview/Agrabah - Events/Lamp Chamber - Defeat Jafar"},
    [2656053] = {"@Overview/Agrabah - Events/Lamp Chamber - Defeat Genie Jafar"},
    [2656054] = {"@Overview/Agrabah - Events/Lamp Chamber - Seal the Keyhole"},
    [2656055] = {"@Overview/Agrabah - Events/Lamp Chamber - Seal the Keyhole"},
    [2656056] = {"@Overview/Agrabah - Events/Lamp Chamber - Seal the Keyhole"},
    [2657018] = {"@Overview/Agrabah - Events/Lamp Chamber - Defeat Genie Jafar"},
    [2656378] = {"@Overview/Agrabah - Events/Desert - Defeat Kurt Zisa"},
    [2657026] = {"@Overview/Agrabah - Events/Desert - Defeat Kurt Zisa"},

    [2652094] = {"@Overview/Cave of Wonders - Chests/Cave Entrance - Left Chest"},
    [2652131] = {"@Overview/Cave of Wonders - Chests/Cave Entrance - Tall Tower Chest"},
    [2652132] = {"@Overview/Cave of Wonders - Chests/Hall - High Left Chest"},
    [2652133] = {"@Overview/Cave of Wonders - Chests/Hall - Chest Near Bottomless Hall"},
    [2652134] = {"@Overview/Cave of Wonders - Chests/Bottomless Hall - Raised Platform Chest"},
    [2652171] = {"@Overview/Cave of Wonders - Chests/Bottomless Hall - Pillar Chest"},
    [2652172] = {"@Overview/Cave of Wonders - Chests/Bottomless Hall - Chest Across Chasm"},
    [2652173] = {"@Overview/Cave of Wonders - Chests/Treasure Room - Chest Across Platforms"},
    [2652174] = {"@Overview/Cave of Wonders - Chests/Treasure Room - Small Treasure Pile Chest"},
    [2652211] = {"@Overview/Cave of Wonders - Chests/Treasure Room - Large Treasure Pile Chest"},
    [2652212] = {"@Overview/Cave of Wonders - Chests/Treasure Room - Chest Above Fire"},
    [2652213] = {"@Overview/Cave of Wonders - Chests/Relic Chamber - Jump from Stairs Chest"},
    [2652214] = {"@Overview/Cave of Wonders - Chests/Relic Chamber - Stairs Chest"},
    [2652251] = {"@Overview/Cave of Wonders - Chests/Dark Chamber - Abu Gem Chest"},
    [2652252] = {"@Overview/Cave of Wonders - Chests/Dark Chamber - Chest Across Relic Chamber Entrance"},
    [2652253] = {"@Overview/Cave of Wonders - Chests/Dark Chamber - Bridge Chest"},
    [2652254] = {"@Overview/Cave of Wonders - Chests/Dark Chamber - Chest Near Save Point"},
    [2652292] = {"@Overview/Cave of Wonders - Chests/Hidden Room - Right Chest"},
    [2652293] = {"@Overview/Cave of Wonders - Chests/Hidden Room - Left Chest"},

    -- Monstro
    [2652452] = {"@Overview/Monstro - Chests Before Movement/Chamber 6 - Low Chest"},
    [2653493] = {"@Overview/Monstro - Chests Before Movement/Mouth - Chest Near Ship"},
    [2653534] = {"@Overview/Monstro - Chests Before Movement/Chamber 2 - Ground Chest"},
    [2653571] = {"@Overview/Monstro - Chests Before Movement/Chamber 2 - Platform Chest"},
    [2653652] = {"@Overview/Monstro - Chests Before Movement/Chamber 3 - Chest Near Chamber 6 Entrance"},
    [2653734] = {"@Overview/Monstro - Chests Before Movement/Chamber 5 - 2nd Low Chest"},
    [2653771] = {"@Overview/Monstro - Chests Before Movement/Chamber 5 - 1st Low Chest"},
    [2653732] = {"@Overview/Monstro - Chests Before Movement/Mouth - Chest on High Platform Near Teeth"},
    [2653614] = {"@Overview/Monstro - Chests Before Movement/Chamber 3 - Ground Chest"},

    [2652413] = {"@Overview/Monstro - Chests After Movement/Chamber 6 - Chest on Platform Opposite Chamber 5 Entrance"},
    [2652414] = {"@Overview/Monstro - Chests After Movement/Chamber 6 - Chest on Platform Near Chamber 5 Entrance"},
    [2652451] = {"@Overview/Monstro - Chests After Movement/Chamber 6 - Chest on Raised Area Near Chamber 1 Entrance"},
    [2653491] = {"@Overview/Monstro - Chests After Movement/Mouth - Chest on High Platform Boat Side"},
    [2653492] = {"@Overview/Monstro - Chests After Movement/Mouth - Chest on High Platform Across from Boat"},
    [2653613] = {"@Overview/Monstro - Chests After Movement/Chamber 5 - Platform Chest"},
    [2653454] = {"@Overview/Monstro - Chests After Movement/Mouth - Boat Deck Chest"},
    [2653651] = {"@Overview/Monstro - Chests After Movement/Chamber 3 - Chest on Platform Above Chamber 2 Entrance"},
    [2653653] = {"@Overview/Monstro - Chests After Movement/Chamber 3 - Chest on Platform Near Chamber 6 Entrance"},
    [2653733] = {"@Overview/Monstro - Chests After Movement/Chamber 5 - Chest Atop Barrel"},

    [2656061] = {"@Overview/Monstro - Events/Bowels - Defeat Parasite Cage"},
    [2656062] = {"@Overview/Monstro - Events/Stomach - Defeat Parasite Cage II"},


  -- Atlantica

    [2652531] = {"@Overview/Atlantica - Chests/Sunken Ship - Chest in Flipped Boat"},
    [2652532] = {"@Overview/Atlantica - Chests/Sunken Ship - Seabed Chest"},
    [2652533] = {"@Overview/Atlantica - Chests/Sunken Ship - Chest Inside Ship"},
    [2652534] = {"@Overview/Atlantica - Chests/Ariel's Grotto - High Chest"},
    [2652571] = {"@Overview/Atlantica - Chests/Ariel's Grotto - Middle Chest"},
    [2652572] = {"@Overview/Atlantica - Chests/Ariel's Grotto - Low Chest"},
    [2652573] = {"@Overview/Atlantica - Chests/Ursula's Lair - Use Fire on Urchin Chest"},
    [2652574] = {"@Overview/Atlantica - Chests/Undersea Gorge - Jammed Chest by Ariel's Grotto"},
    [2656201] = {"@Overview/Atlantica - Clams/Undersea Gorge - Blizzard Clam"},
    [2656202] = {"@Overview/Atlantica - Clams/Undersea Gorge - Ocean Floor Clam"},
    [2656203] = {"@Overview/Atlantica - Clams/Undersea Valley - Higher Cave Clam"},
    [2656204] = {"@Overview/Atlantica - Clams/Undersea Valley - Lower Cave Clam"},
    [2656205] = {"@Overview/Atlantica - Clams/Undersea Valley - Fire Clam"},
    [2656206] = {"@Overview/Atlantica - Clams/Undersea Valley - Wall Clam"},
    [2656207] = {"@Overview/Atlantica - Clams/Undersea Valley - Pillar Clam"},
    [2656208] = {"@Overview/Atlantica - Clams/Undersea Valley - Ocean Floor Clam"},
    [2656209] = {"@Overview/Atlantica - Clams/Triton's Palace - Thunder Clam"},
    [2656210] = {"@Overview/Atlantica - Clams/Triton's Palace - Right Wall Clam"},
    [2656211] = {"@Overview/Atlantica - Clams/Triton's Palace - Clam Near Path"},
    [2656212] = {"@Overview/Atlantica - Clams/Triton's Palace - Left Wall Clam"},
    [2656213] = {"@Overview/Atlantica - Clams/Cavern Nook - Clam"},
    [2656214] = {"@Overview/Atlantica - Clams/Sunken Ship - Clam Below Deck"},
    [2656215] = {"@Overview/Atlantica - Clams/Undersea Garden - Clam"},
    [2656216] = {"@Overview/Atlantica - Clams/Undersea Cave - Clam"},
    [2656381] = {"@Overview/Atlantica - Events/Sunken Ship - Obtain Crystal Trident"},
    [2656071] = {"@Overview/Atlantica - Events/Ursula's Lair - Defeat Ursula I"},
    [2656072] = {"@Overview/Atlantica - Events/Ursula's Lair II - Defeat Ursula II"},
    [2657016] = {"@Overview/Atlantica - Events/Ursula's Lair II - Defeat Ursula II"},
    [2656073] = {"@Overview/Atlantica - Events/Ariel's Grotto - Seal Atlantica Keyhole"},

    [2653052] = {"@Overview/Halloween Town - Before Jack-in-the-Box/Boneyard - Tombstone Puzzle Chest"},
    [2653133] = {"@Overview/Halloween Town - Before Jack-in-the-Box/Guillotine Square - High Tower Chest"},
    [2653134] = {"@Overview/Halloween Town - Before Jack-in-the-Box/Guillotine Square - Left Chest in Pumpkin Structure"},
    [2653293] = {"@Overview/Halloween Town - Before Jack-in-the-Box/Guillotine Square - Chest Under Jack's House"},
    [2653294] = {"@Overview/Halloween Town - Before Jack-in-the-Box/Guillotine Square - Right Chest in Pumpkin Structure"},
    [2656331] = {"@Overview/Halloween Town - Before Jack-in-the-Box/Guillotine Square - Ring Jack's Doorbell 3 Times"},
    [2656382] = {"@Overview/Halloween Town - Before Jack-in-the-Box/Graveyard - Obtain Forget-Me-Not"},
    [2656508] = {"@Overview/Halloween Town - Before Jack-in-the-Box/Lab - Torn Page in Book"},

    [2653051] = {"@Overview/Halloween Town - After Jack-in-the-Box/Bridge - Chest Under Bridge"},
    [2653053] = {"@Overview/Halloween Town - After Jack-in-the-Box/Bridge - Chest Right of Gate"},
    [2653054] = {"@Overview/Halloween Town - After Jack-in-the-Box/Cemetery - Chest Behind Grave"},
    [2653091] = {"@Overview/Halloween Town - After Jack-in-the-Box/Cemetery - Chest By Cat Shaped Grave"},
    [2653092] = {"@Overview/Halloween Town - After Jack-in-the-Box/Cemetery - Chest Between Graves"},
    [2653093] = {"@Overview/Halloween Town - After Jack-in-the-Box/Oogie's Manor - Chest in Lower Iron Cage"},
    [2653094] = {"@Overview/Halloween Town - After Jack-in-the-Box/Oogie's Manor - Chest in Upper Iron Cage"},
    [2653131] = {"@Overview/Halloween Town - After Jack-in-the-Box/Oogie's Manor - Hollow Chest"},
    [2653171] = {"@Overview/Halloween Town - After Jack-in-the-Box/Oogie's Manor - Chest at Entrance Steps"},
    [2653172] = {"@Overview/Halloween Town - After Jack-in-the-Box/Oogie's Manor - Chest Inside Entrance"},
    [2653291] = {"@Overview/Halloween Town - After Jack-in-the-Box/Bridge - Chest Left of Gate"},
    [2653292] = {"@Overview/Halloween Town - After Jack-in-the-Box/Cemetery - Chest by Striped Grave"},
    [2656081] = {"@Overview/Halloween Town - After Jack-in-the-Box/Torture Chamber - Defeat Oogie Boogie"},
    [2656082] = {"@Overview/Halloween Town - After Jack-in-the-Box/Oogie's Manor - Defeat Oogie's Manor"},
    [2656083] = {"@Overview/Halloween Town - After Jack-in-the-Box/Oogie's Manor - Defeat Oogie's Manor"},
    [2657012] = {"@Overview/Halloween Town - After Jack-in-the-Box/Torture Chamber - Defeat Oogie Boogie"},


    -- Neverland
    [2653773] = {"@Overview/Neverland - Chests/Pirate Ship - Chest in Crows Nest"},
    [2653774] = {"@Overview/Neverland - Chests/Hold - Right Blue Chest"},
    [2653811] = {"@Overview/Neverland - Chests/Hold - Left Blue Chest"},
    [2653812] = {"@Overview/Neverland - Chests/Galley - Chest"},
    [2653813] = {"@Overview/Neverland - Chests/Cabin - Chest"},
    [2653814] = {"@Overview/Neverland - Chests/Hold - 1st Chest on Beam"},
    [2654014] = {"@Overview/Neverland - Chests/Clock Tower - Chest"},
    [2654051] = {"@Overview/Neverland - Chests/Hold - 2nd Chest on Beam"},
    [2654052] = {"@Overview/Neverland - Chests/Hold - Green Chest"},
    [2654053] = {"@Overview/Neverland - Chests/Captain's Cabin - Chest"},
    [2656344] = {"@Overview/Neverland - Chests/Hold - Red Chest"},
    [2656091] = {"@Overview/Neverland - Events/Captain's Cabin - Defeat Anti Sora"},
    [2656092] = {"@Overview/Neverland - Events/Pirate Ship - Encounter Captain Hook"},
    [2656093] = {"@Overview/Neverland - Events/Clock Tower - Seal Keyhole"},
    [2656094] = {"@Overview/Neverland - Events/Clock Tower - Seal Keyhole"},
    [2656095] = {"@Overview/Neverland - Events/Clock Tower - Seal Keyhole"},
    [2656096] = {"@Overview/Neverland - Events/Clock Tower - Defeat Phantom"},
    [2656097] = {"@Overview/Neverland - Events/Pirate Ship - Defeat Captain Hook"},
    [2657028] = {"@Overview/Neverland - Events/Pirate Ship - Defeat Captain Hook"},
    [2656332] = {"@Overview/Neverland - Chests/Clock Tower - 01:00 Door"},
    [2656333] = {"@Overview/Neverland - Chests/Clock Tower - 02:00 Door"},
    [2656334] = {"@Overview/Neverland - Chests/Clock Tower - 03:00 Door"},
    [2656335] = {"@Overview/Neverland - Chests/Clock Tower - 04:00 Door"},
    [2656336] = {"@Overview/Neverland - Chests/Clock Tower - 05:00 Door"},
    [2656337] = {"@Overview/Neverland - Chests/Clock Tower - 06:00 Door"},
    [2656338] = {"@Overview/Neverland - Chests/Clock Tower - 07:00 Door"},
    [2656339] = {"@Overview/Neverland - Chests/Clock Tower - 08:00 Door"},
    [2656340] = {"@Overview/Neverland - Chests/Clock Tower - 09:00 Door"},
    [2656341] = {"@Overview/Neverland - Chests/Clock Tower - 10:00 Door"},
    [2656342] = {"@Overview/Neverland - Chests/Clock Tower - 11:00 Door"},
    [2656343] = {"@Overview/Neverland - Chests/Clock Tower - 12:00 Door"},

    --Hollow Bastion
    [2654054] = {"@Overview/Hollow Bastion - Before Emblems/Rising Falls - Chest on Water Surface"},
    [2654091] = {"@Overview/Hollow Bastion - Before Emblems/Rising Falls - 1st Chest Under Water"},
    [2654093] = {"@Overview/Hollow Bastion - Before Emblems/Rising Falls - Chest on Floating Platform Near Save Point"},
    [2654094] = {"@Overview/Hollow Bastion - Before Emblems/Rising Falls - Chest on Floating Platform Near Bubble"},
    [2654131] = {"@Overview/Hollow Bastion - Before Emblems/Rising Falls - High Platform Chest"},
    [2654331] = {"@Overview/Hollow Bastion - Before Emblems/Base Level - Use Bubble to Move Under the Wall"},
    [2654332] = {"@Overview/Hollow Bastion - Before Emblems/Base Level - Chest on Platform Near Entrance"},
    [2654333] = {"@Overview/Hollow Bastion - Before Emblems/Base Level - Chest Near Crystal Switch"},
    [2654334] = {"@Overview/Hollow Bastion - Before Emblems/Waterway - Chest Near Save"},
    [2654371] = {"@Overview/Hollow Bastion - Before Emblems/Waterway - Chest Atop Passageway"},
    [2654372] = {"@Overview/Hollow Bastion - Before Emblems/Waterway - Unlock Passage from Base Level"},
    [2654373] = {"@Overview/Hollow Bastion - Before Emblems/Dungeon - Chest by Candles"},
    [2654374] = {"@Overview/Hollow Bastion - Before Emblems/Dungeon - Chest in Corner"},
    [2654213] = {"@Overview/Hollow Bastion - Before Emblems/Library - Chest on Bookshelf"},
    [2654291] = {"@Overview/Hollow Bastion - Before Emblems/Lift Stop - Gravity Chest in Library Node"},
    [2654293] = {"@Overview/Hollow Bastion - Before Emblems/Lift Stop - Gravity Chest Behind Library Bookshelf"},
    [2654212] = {"@Overview/Hollow Bastion - Before Emblems/Entrance Hall - Chest on Pillar Before Emblem Door"},
    [2654214] = {"@Overview/Hollow Bastion - Before Emblems/Library - Turning Carousel Chest on 1st Floor"},
    [2654251] = {"@Overview/Hollow Bastion - Before Emblems/Library - Turning Carousel Chest on Top of Bookshelf"},
    [2654252] = {"@Overview/Hollow Bastion - Before Emblems/Library - 1st Turning Carousel Chest on 2nd Floor"},
    [2654253] = {"@Overview/Hollow Bastion - Before Emblems/Library - 2nd Turning Carousel Chest on 2nd Floor"},
    [2656101] = {"@Overview/Hollow Bastion - Before Emblems/Entrance Hall - Defeat Riku I"},
    [2656516] = {"@Overview/Hollow Bastion - Before Emblems/Entrance Hall - Emblem Piece (Flame)"},
    [2656517] = {"@Overview/Hollow Bastion - Before Emblems/Entrance Hall - Emblem Piece (Chest)"},
    [2656518] = {"@Overview/Hollow Bastion - Before Emblems/Entrance Hall - Emblem Piece (Statue)"},
    [2656519] = {"@Overview/Hollow Bastion - Before Emblems/Entrance Hall - Emblem Piece (Fountain)"},
    [2656623] = {"@Overview/Hollow Bastion - Lift Stop from Waterway Examine Node"},

    [2654132] = {"@Overview/Hollow Bastion - After Emblems/Castle Gates - Gravity Chest"},
    [2654133] = {"@Overview/Hollow Bastion - After Emblems/Castle Gates - Chest on Freestanding Pillar"},
    [2654134] = {"@Overview/Hollow Bastion - After Emblems/Castle Gates - Chest on High Pillar"},
    [2654171] = {"@Overview/Hollow Bastion - After Emblems/Great Crest - Lower Chest"},
    [2654172] = {"@Overview/Hollow Bastion - After Emblems/Great Crest - Chest after Battle Platform"},
    [2654173] = {"@Overview/Hollow Bastion - After Emblems/High Tower - 2nd Gravity Chest"},
    [2654174] = {"@Overview/Hollow Bastion - After Emblems/High Tower - 1st Gravity Chest"},
    [2654211] = {"@Overview/Hollow Bastion - After Emblems/High Tower - Chest Above Sliding Blocks"},
    [2654254] = {"@Overview/Hollow Bastion - After Emblems/Lift Stop - Gravity Chest in Library Node After High Tower Switch"},
    [2654292] = {"@Overview/Hollow Bastion - After Emblems/Lift Stop - Gravity Chest Under High Tower Sliding Blocks"},
    [2654294] = {"@Overview/Hollow Bastion - After Emblems/Lift Stop - Gravity Chest Behind Heartless Sigil Door"},
    [2656102] = {"@Overview/Hollow Bastion - After Emblems/Castle Chapel - Defeat Maleficent"},
    [2657014] = {"@Overview/Hollow Bastion - After Emblems/Castle Chapel - Defeat Maleficent"},
    [2656103] = {"@Overview/Hollow Bastion - After Emblems/Castle Chapel - Defeat Dragon Maleficent"},
    [2656104] = {"@Overview/Hollow Bastion - After Emblems/Grand Hall - Defeat Riku II"},

    [2654092] = {"@Overview/Hollow Bastion - 2nd Visit/Rising Falls - 2nd Chest Under Water"},
    [2654454] = {"@Overview/Hollow Bastion - 2nd Visit/Grand Hall - Chest on Right Side Steps"},
    [2654491] = {"@Overview/Hollow Bastion - 2nd Visit/Grand Hall - Oblivion Chest"},
    [2654492] = {"@Overview/Hollow Bastion - 2nd Visit/Grand Hall - Chest Left of Gate"},
    [2656105] = {"@Overview/Hollow Bastion - 2nd Visit/Grand Hall - Defeat Behemoth"},
    [2656106] = {"@Overview/Hollow Bastion - 2nd Visit/Castle Chapel - Talk to the Princesses"},
    [2656379] = {"@Overview/Hollow Bastion - 2nd Visit/Castle Chapel - Defeat Unknown"},
    [2657024] = {"@Overview/Hollow Bastion - 2nd Visit/Castle Chapel - Defeat Unknown"},
    [2656522] = {"@Overview/Hollow Bastion - 2nd Visit/Library - Talk to Belle"},
    [2656523] = {"@Overview/Hollow Bastion - 2nd Visit/Library - Talk to Aerith"},
    [2657013] = {"@Overview/Hollow Bastion - 2nd Visit/Library - Talk to Aerith"},
    [2657015] = {"@Overview/Hollow Bastion - 2nd Visit/Library - Talk to Aerith"},
    [2657017] = {"@Overview/Hollow Bastion - 2nd Visit/Library - Talk to Aerith"},
    [2657027] = {"@Overview/Hollow Bastion - 2nd Visit/Library - Talk to Aerith"},

    -- End of the World
    [2654531] = {"@Overview/End of the World - Final Dimension/Final Dimension - 1st Chest"},
    [2654532] = {"@Overview/End of the World - Final Dimension/Final Dimension - 2nd Chest"},
    [2654533] = {"@Overview/End of the World - Final Dimension/Final Dimension - 3rd Chest"},
    [2654534] = {"@Overview/End of the World - Final Dimension/Final Dimension - 4th Chest"},
    [2654571] = {"@Overview/End of the World - Final Dimension/Final Dimension - 5th Chest"},
    [2654572] = {"@Overview/End of the World - Final Dimension/Final Dimension - 6th Chest"},
    [2654612] = {"@Overview/End of the World - Final Dimension/Final Dimension - 7th Chest"},
    [2654611] = {"@Overview/End of the World - Final Dimension/Final Dimension - 8th Chest"},
    [2654574] = {"@Overview/End of the World - Final Dimension/Final Dimension - 9th Chest"},
    [2654573] = {"@Overview/End of the World - Final Dimension/Final Dimension - 10th Chest"},
    [2654651] = {"@Overview/End of the World - Final Dimension/Giant Crevasse - 1st Chest"},
    [2654653] = {"@Overview/End of the World - Final Dimension/Giant Crevasse - 2nd Chest"},
    [2654613] = {"@Overview/End of the World - Final Dimension/Giant Crevasse - 3rd Chest"},
    [2654652] = {"@Overview/End of the World - Final Dimension/Giant Crevasse - 4th Chest"},
    [2654614] = {"@Overview/End of the World - Final Dimension/Giant Crevasse - 5th Chest"},
    [2654654] = {"@Overview/End of the World - World Terminus/World Terminus - Traverse Town Chest"},
    [2654691] = {"@Overview/End of the World - World Terminus/World Terminus - Wonderland Chest"},
    [2654692] = {"@Overview/End of the World - World Terminus/World Terminus - Olympus Coliseum Chest"},
    [2654693] = {"@Overview/End of the World - World Terminus/World Terminus - Deep Jungle Chest"},
    [2654694] = {"@Overview/End of the World - World Terminus/World Terminus - Agrabah Chest"},
    [2654731] = {"@Overview/End of the World - World Terminus/World Terminus - Atlantica Chest"},
    [2654732] = {"@Overview/End of the World - World Terminus/World Terminus - Halloween Town Chest"},
    [2654733] = {"@Overview/End of the World - World Terminus/World Terminus - Neverland Chest"},
    [2654734] = {"@Overview/End of the World - World Terminus/World Terminus - 100 Acre Wood Chest"},
    [2654771] = {"@Overview/End of the World - World Terminus/World Terminus - Hollow Bastion Chest"},
    [2654772] = {"@Overview/End of the World - World Terminus/Final Rest - Chest"},
    [2656111] = {"@Overview/End of the World - World Terminus/World Terminus - Defeat Chernabog"},

    -- 100 Acre Wood
    [2651654] = {"@Overview/Hundred Acre Wood/Meadow - Chest Inside Log"},
    [2651691] = {"@Overview/Hundred Acre Wood/Bouncing Spot - Chest on Cliff on Left Side"},
    [2651692] = {"@Overview/Hundred Acre Wood/Bouncing Spot - Chest in Tree Alcove"},
    [2651693] = {"@Overview/Hundred Acre Wood/Bouncing Spot - Chest in Tree Stump"},
    [2656345] = {"@Overview/Hundred Acre Wood/Bouncing Spot - Turn in Rare Nut #1"},
    [2656346] = {"@Overview/Hundred Acre Wood/Bouncing Spot - Turn in Rare Nut #2"},
    [2656347] = {"@Overview/Hundred Acre Wood/Bouncing Spot - Turn in Rare Nut #3"},
    [2656348] = {"@Overview/Hundred Acre Wood/Bouncing Spot - Turn in Rare Nut #4"},
    [2656349] = {"@Overview/Hundred Acre Wood/Bouncing Spot - Turn in Rare Nut #5"},
    [2656350] = {"@Overview/Hundred Acre Wood/Pooh's House - Talk to Owl"},
    [2656356] = {"@Overview/Hundred Acre Wood/Pooh's House - Light the Fire"},
    [2656357] = {"@Overview/Hundred Acre Wood/Pooh's House - Open Cabinet"},
    [2656358] = {"@Overview/Hundred Acre Wood/Pooh's House - Strike Chimney"},
    [2656359] = {"@Overview/Hundred Acre Wood/Bouncing Spot - Break the Log"},
    [2656360] = {"@Overview/Hundred Acre Wood/Bouncing Spot - Use the Seesaw"},
    [2656351] = {"@Overview/Hundred Acre Wood/Convert Torn Page #1"},
    [2656352] = {"@Overview/Hundred Acre Wood/Convert Torn Page #2"},
    [2656353] = {"@Overview/Hundred Acre Wood/Convert Torn Page #3"},
    [2656354] = {"@Overview/Hundred Acre Wood/Convert Torn Page #4"},
    [2656355] = {"@Overview/Hundred Acre Wood/Convert Torn Page #5"},

    -- Synth Items
    [2656400] = {"@Overview/Traverse Town - Moogle Workshop/Synth 15 Items"},
    [2656407] = {"@Overview/Traverse Town - Moogle Workshop/Synth Item 07"},
    [2656408] = {"@Overview/Traverse Town - Moogle Workshop/Synth Item 08"},
    [2656409] = {"@Overview/Traverse Town - Moogle Workshop/Synth Item 09"},
    [2656410] = {"@Overview/Traverse Town - Moogle Workshop/Synth Item 10"},
    [2656411] = {"@Overview/Traverse Town - Moogle Workshop/Synth Item 11"},
    [2656412] = {"@Overview/Traverse Town - Moogle Workshop/Synth Item 12"},
    [2656413] = {"@Overview/Traverse Town - Moogle Workshop/Synth Item 13"},
    [2656414] = {"@Overview/Traverse Town - Moogle Workshop/Synth Item 14"},
    [2656415] = {"@Overview/Traverse Town - Moogle Workshop/Synth Item 15"},
    [2656416] = {"@Overview/Traverse Town - Moogle Workshop/Synth Item 16"},
    [2656417] = {"@Overview/Traverse Town - Moogle Workshop/Synth Item 17"},
    [2656418] = {"@Overview/Traverse Town - Moogle Workshop/Synth Item 18"},
    [2656419] = {"@Overview/Traverse Town - Moogle Workshop/Synth Item 19"},
    [2656420] = {"@Overview/Traverse Town - Moogle Workshop/Synth Item 20"},
    [2656421] = {"@Overview/Traverse Town - Moogle Workshop/Synth Item 21"},
    [2656422] = {"@Overview/Traverse Town - Moogle Workshop/Synth Item 22"},
    [2656423] = {"@Overview/Traverse Town - Moogle Workshop/Synth Item 23"},
    [2656424] = {"@Overview/Traverse Town - Moogle Workshop/Synth Item 24"},
    [2656425] = {"@Overview/Traverse Town - Moogle Workshop/Synth Item 25"},
    [2656426] = {"@Overview/Traverse Town - Moogle Workshop/Synth Item 26"},
    [2656427] = {"@Overview/Traverse Town - Moogle Workshop/Synth Item 27"},
    [2656428] = {"@Overview/Traverse Town - Moogle Workshop/Synth Item 28"},
    [2656429] = {"@Overview/Traverse Town - Moogle Workshop/Synth Item 29"},
    [2656430] = {"@Overview/Traverse Town - Moogle Workshop/Synth Item 30"},
    [2656431] = {"@Overview/Traverse Town - Moogle Workshop/Synth Item 31"},
    [2656432] = {"@Overview/Traverse Town - Moogle Workshop/Synth Item 32"},
    [2656433] = {"@Overview/Traverse Town - Moogle Workshop/Synth Item 33"},

    -- Trinities
    [2653333] = {"@Overview/Olympus Coliseum - Before Entry Pass/Coliseum Gates - Right Blue Trinity Chest"},
    [2653334] = {"@Overview/Olympus Coliseum - Before Entry Pass/Coliseum Gates - Left Blue Trinity Chest"},
    [2656600] = {"@Overview/Traverse Town - Further Visits/1st District - Blue Trinity Exit"},
    [2656601] = {"@Overview/Traverse Town - Further Visits/3rd District - Blue Trinity"},
    [2656602] = {"@Overview/Traverse Town - Further Visits/Mystical House - Blue Trinity"},
    [2650411] = {"@Overview/Traverse Town - Further Visits/1st District - Blue Trinity Balcony Chest"},
    [2656609] = {"@Overview/Hollow Bastion - Before Emblems/Dungeon - Blue Trinity"},
    [2656608] = {"@Overview/Hollow Bastion - After Emblems/Great Crest - Blue Trinity"},
    [2651293] = {"@Overview/Deep Jungle - Before Slides/Climbing Trees - Blue Trinity Chest"},
    [2651333] = {"@Overview/Deep Jungle - Before Slides/Camp - Blue Trinity Chest"},
    [2656612] = {"@Overview/Monstro - Chests After Movement/Throat - Blue Trinity"},
    [2656606] = {"@Overview/Monstro - Chests After Movement/Mouth - Blue Trinity"},
    [2656607] = {"@Overview/Monstro - Chests Before Movement/Chamber 5 - Blue Trinity"},
    [2652291] = {"@Overview/Cave of Wonders - Chests/Silent Chamber - Blue Trinity Chest"},
    [2656605] = {"@Overview/Agrabah - Chests/Bazaar - Blue Trinity"},

    [2652092] = {"@Overview/Agrabah - Chests/Storage - Green Trinity Chest"},
    [2656377] = {"@Overview/Olympus Coliseum - Before Entry Pass/Coliseum Gates - Green Trinity"},
    [2656610] = {"@Overview/Deep Jungle - Before Slides/Treetop - Green Trinity"},
    [2650931] = {"@Overview/Wonderland - Before Footprints/Rabbit Hole - Green Trinity Chest"},
    [2650971] = {"@Overview/Wonderland - Before Footprints/Bizarre Room - Green Trinity Chest"},
    [2653494] = {"@Overview/Monstro - Chests After Movement/Mouth - Green Trinity Chest"},

    [2653132] = {"@Overview/Halloween Town - After Jack-in-the-Box/Oogie's Manor - Red Trinity Chest"},
    [2656611] = {"@Overview/Cave of Wonders - Chests/Treasure Room - Red Trinity"},

    [2650331] = {"@Overview/Traverse Town - Further Visits/Mystical House - Yellow Trinity Chest"},

    [2650333] = {"@Overview/Traverse Town - Further Visits/Secret Waterway - White Trinity Chest"},
    [2654494] = {"@Overview/Hollow Bastion - Before Emblems/Rising Falls - White Trinity Chest"},
    [2653772] = {"@Overview/Neverland - Chests/Pirate Ship - White Trinity Chest on Deck"},
    [2653014] = {"@Overview/Halloween Town - Before Jack-in-the-Box/Moonlight Hill - White Trinity Chest"},
    [2652611] = {"@Overview/Atlantica - Chests/Triton's Palace - White Trinity Chest"},
    [2655092] = {"@Overview/Monstro - Chests Before Movement/Chamber 6 - White Trinity Chest"},
    [2652332] = {"@Overview/Cave of Wonders - Chests/Cave Entrance - White Trinity Chest"},
    [2653371] = {"@Overview/Olympus Coliseum - Before Entry Pass/Coliseum Gates - White Trinity Chest"},
    [2651332] = {"@Overview/Deep Jungle - After Slides/Cavern of Hearts - White Trinity Chest"},
    [2651133] = {"@Overview/Wonderland - After Footprints/Lotus Forest - White Trinity Chest"},

    -- Destiny Islands
    [2656704] = {"@Overview/Destiny Islands/Seashore - Log on Riku's Island (Day 1)"},
    [2656705] = {"@Overview/Destiny Islands/Seashore - Log under Bridge (Day 1)"},
    [2656706] = {"@Overview/Destiny Islands/Seashore - Gather Cloth (Day 1)"},
    [2656707] = {"@Overview/Destiny Islands/Seashore - Gather Rope (Day 1)"},

    -- Party Member Starting Accessories
    [2656801] = {"@Overview/Party/Donald/Starting Accessory 2"},
    [2656802] = {"@Overview/Party/Goofy/Starting Accessory 1"},
    [2656803] = {"@Overview/Party/Goofy/Starting Accessory 2"},
    [2656804] = {"@Overview/Party/Tarzan/Starting Accessory 1"},
    [2656810] = {"@Overview/Party/Jack/Starting Accessory 1"},
    [2656812] = {"@Overview/Party/Peter Pan/Starting Accessory 1"},
    [2656813] = {"@Overview/Party/Peter Pan/Starting Accessory 2"},
    [2656814] = {"@Overview/Party/Beast/Starting Accessory 1"},

    -- Level Rewards (Slot 1)
    [2658002] = {"@Overview/Level Rewards/Level 002 (Slot 1)"},
    [2658003] = {"@Overview/Level Rewards/Level 003 (Slot 1)"},
    [2658004] = {"@Overview/Level Rewards/Level 004 (Slot 1)"},
    [2658005] = {"@Overview/Level Rewards/Level 005 (Slot 1)"},
    [2658006] = {"@Overview/Level Rewards/Level 006 (Slot 1)"},
    [2658007] = {"@Overview/Level Rewards/Level 007 (Slot 1)"},
    [2658008] = {"@Overview/Level Rewards/Level 008 (Slot 1)"},
    [2658009] = {"@Overview/Level Rewards/Level 009 (Slot 1)"},
    [2658010] = {"@Overview/Level Rewards/Level 010 (Slot 1)"},
    [2658011] = {"@Overview/Level Rewards/Level 011 (Slot 1)"},
    [2658012] = {"@Overview/Level Rewards/Level 012 (Slot 1)"},
    [2658013] = {"@Overview/Level Rewards/Level 013 (Slot 1)"},
    [2658014] = {"@Overview/Level Rewards/Level 014 (Slot 1)"},
    [2658015] = {"@Overview/Level Rewards/Level 015 (Slot 1)"},
    [2658016] = {"@Overview/Level Rewards/Level 016 (Slot 1)"},
    [2658017] = {"@Overview/Level Rewards/Level 017 (Slot 1)"},
    [2658018] = {"@Overview/Level Rewards/Level 018 (Slot 1)"},
    [2658019] = {"@Overview/Level Rewards/Level 019 (Slot 1)"},
    [2658020] = {"@Overview/Level Rewards/Level 020 (Slot 1)"},
    [2658021] = {"@Overview/Level Rewards/Level 021 (Slot 1)"},
    [2658022] = {"@Overview/Level Rewards/Level 022 (Slot 1)"},
    [2658023] = {"@Overview/Level Rewards/Level 023 (Slot 1)"},
    [2658024] = {"@Overview/Level Rewards/Level 024 (Slot 1)"},
    [2658025] = {"@Overview/Level Rewards/Level 025 (Slot 1)"},
    [2658026] = {"@Overview/Level Rewards/Level 026 (Slot 1)"},
    [2658027] = {"@Overview/Level Rewards/Level 027 (Slot 1)"},
    [2658028] = {"@Overview/Level Rewards/Level 028 (Slot 1)"},
    [2658029] = {"@Overview/Level Rewards/Level 029 (Slot 1)"},
    [2658030] = {"@Overview/Level Rewards/Level 030 (Slot 1)"},
    [2658031] = {"@Overview/Level Rewards/Level 031 (Slot 1)"},
    [2658032] = {"@Overview/Level Rewards/Level 032 (Slot 1)"},
    [2658033] = {"@Overview/Level Rewards/Level 033 (Slot 1)"},
    [2658034] = {"@Overview/Level Rewards/Level 034 (Slot 1)"},
    [2658035] = {"@Overview/Level Rewards/Level 035 (Slot 1)"},
    [2658036] = {"@Overview/Level Rewards/Level 036 (Slot 1)"},
    [2658037] = {"@Overview/Level Rewards/Level 037 (Slot 1)"},
    [2658038] = {"@Overview/Level Rewards/Level 038 (Slot 1)"},
    [2658039] = {"@Overview/Level Rewards/Level 039 (Slot 1)"},
    [2658040] = {"@Overview/Level Rewards/Level 040 (Slot 1)"},
    [2658041] = {"@Overview/Level Rewards/Level 041 (Slot 1)"},
    [2658042] = {"@Overview/Level Rewards/Level 042 (Slot 1)"},
    [2658043] = {"@Overview/Level Rewards/Level 043 (Slot 1)"},
    [2658044] = {"@Overview/Level Rewards/Level 044 (Slot 1)"},
    [2658045] = {"@Overview/Level Rewards/Level 045 (Slot 1)"},
    [2658046] = {"@Overview/Level Rewards/Level 046 (Slot 1)"},
    [2658047] = {"@Overview/Level Rewards/Level 047 (Slot 1)"},
    [2658048] = {"@Overview/Level Rewards/Level 048 (Slot 1)"},
    [2658049] = {"@Overview/Level Rewards/Level 049 (Slot 1)"},
    [2658050] = {"@Overview/Level Rewards/Level 050 (Slot 1)"},
    [2658051] = {"@Overview/Level Rewards/Level 051 (Slot 1)"},
    [2658052] = {"@Overview/Level Rewards/Level 052 (Slot 1)"},
    [2658053] = {"@Overview/Level Rewards/Level 053 (Slot 1)"},
    [2658054] = {"@Overview/Level Rewards/Level 054 (Slot 1)"},
    [2658055] = {"@Overview/Level Rewards/Level 055 (Slot 1)"},
    [2658056] = {"@Overview/Level Rewards/Level 056 (Slot 1)"},
    [2658057] = {"@Overview/Level Rewards/Level 057 (Slot 1)"},
    [2658058] = {"@Overview/Level Rewards/Level 058 (Slot 1)"},
    [2658059] = {"@Overview/Level Rewards/Level 059 (Slot 1)"},
    [2658060] = {"@Overview/Level Rewards/Level 060 (Slot 1)"},
    [2658061] = {"@Overview/Level Rewards/Level 061 (Slot 1)"},
    [2658062] = {"@Overview/Level Rewards/Level 062 (Slot 1)"},
    [2658063] = {"@Overview/Level Rewards/Level 063 (Slot 1)"},
    [2658064] = {"@Overview/Level Rewards/Level 064 (Slot 1)"},
    [2658065] = {"@Overview/Level Rewards/Level 065 (Slot 1)"},
    [2658066] = {"@Overview/Level Rewards/Level 066 (Slot 1)"},
    [2658067] = {"@Overview/Level Rewards/Level 067 (Slot 1)"},
    [2658068] = {"@Overview/Level Rewards/Level 068 (Slot 1)"},
    [2658069] = {"@Overview/Level Rewards/Level 069 (Slot 1)"},
    [2658070] = {"@Overview/Level Rewards/Level 070 (Slot 1)"},
    [2658071] = {"@Overview/Level Rewards/Level 071 (Slot 1)"},
    [2658072] = {"@Overview/Level Rewards/Level 072 (Slot 1)"},
    [2658073] = {"@Overview/Level Rewards/Level 073 (Slot 1)"},
    [2658074] = {"@Overview/Level Rewards/Level 074 (Slot 1)"},
    [2658075] = {"@Overview/Level Rewards/Level 075 (Slot 1)"},
    [2658076] = {"@Overview/Level Rewards/Level 076 (Slot 1)"},
    [2658077] = {"@Overview/Level Rewards/Level 077 (Slot 1)"},
    [2658078] = {"@Overview/Level Rewards/Level 078 (Slot 1)"},
    [2658079] = {"@Overview/Level Rewards/Level 079 (Slot 1)"},
    [2658080] = {"@Overview/Level Rewards/Level 080 (Slot 1)"},
    [2658081] = {"@Overview/Level Rewards/Level 081 (Slot 1)"},
    [2658082] = {"@Overview/Level Rewards/Level 082 (Slot 1)"},
    [2658083] = {"@Overview/Level Rewards/Level 083 (Slot 1)"},
    [2658084] = {"@Overview/Level Rewards/Level 084 (Slot 1)"},
    [2658085] = {"@Overview/Level Rewards/Level 085 (Slot 1)"},
    [2658086] = {"@Overview/Level Rewards/Level 086 (Slot 1)"},
    [2658087] = {"@Overview/Level Rewards/Level 087 (Slot 1)"},
    [2658088] = {"@Overview/Level Rewards/Level 088 (Slot 1)"},
    [2658089] = {"@Overview/Level Rewards/Level 089 (Slot 1)"},
    [2658090] = {"@Overview/Level Rewards/Level 090 (Slot 1)"},
    [2658091] = {"@Overview/Level Rewards/Level 091 (Slot 1)"},
    [2658092] = {"@Overview/Level Rewards/Level 092 (Slot 1)"},
    [2658093] = {"@Overview/Level Rewards/Level 093 (Slot 1)"},
    [2658094] = {"@Overview/Level Rewards/Level 094 (Slot 1)"},
    [2658095] = {"@Overview/Level Rewards/Level 095 (Slot 1)"},
    [2658096] = {"@Overview/Level Rewards/Level 096 (Slot 1)"},
    [2658097] = {"@Overview/Level Rewards/Level 097 (Slot 1)"},
    [2658098] = {"@Overview/Level Rewards/Level 098 (Slot 1)"},
    [2658099] = {"@Overview/Level Rewards/Level 099 (Slot 1)"},
    [2658100] = {"@Overview/Level Rewards/Level 100 (Slot 1)"}
}